const Map<String, String> enUS = {
  "english_lables_of_partner_app": "English lables of Partner App",
  "choose_your_language": "Choose Your Language",
  "english": "English",
  "arabic": "Arabic",
  "continue": "Continue",
  "partner_login": "Partner Login",
  "userid": "UserId",
  "enter_your_user_id": "Enter your user id",
  "password": "Password",
  "enter_your_password": "Enter your password",
  "login": "Login",
  "user_id_is_required": "User ID is required",
  "password_is_required": "Password is required",
  "invalid_credentials": "Invalid credentials",
  "home": "Home",
  "history": "History",
  "profile": "Profile",
  "tap_to_scan": "Tap to scan",
  "scan_customer_qr_code": "Scan Customer QR Code",
  "previous_service": "Previous Service",
  "no_previous_services": "No previous services",
  "customer": "Customer:",
  "vehicle": "Vehicle:",
  "admin_payable": "Admin Payable:",
  "service_history": "Service History",
  "search_service_name_or_customer_name":
      "Search service name or customer name",
  "recent_activity": "Recent Activity",
  "no_history_found": "No history found",
  "total_admin_payable": "Total Admin Payable",
  "jan": "Jan",
  "feb": "Feb",
  "mar": "Mar",
  "april": "April",
  "may": "may",
  "jun": "jun",
  "jul": "jul",
  "aug": "Aug",
  "sep": "Sep",
  "oct": "Oct",
  "nov": "Nov",
  "dec": "Dec",
  "date": "DATE",
  "partner": "PARTNER",
  "owner": "Owner:",
  "account_settings": "ACCOUNT SETTINGS",
  "personal_details": "Personal Details",
  "edit_profile_information": "Edit profile information",
  "add_services": "Add Services",
  "add_or_remove_services_offered": "Add or remove services offered",
  "change_password": "Change Password",
  "update_security_credentials": "Update security credentials",
  "change_language": "Change Language",
  "log_out": "Log Out",
  "sign_out_of_your_account": "Sign out of your account",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "cancel": "Cancel",
  "add_new_service": "Add New Service",
  "edit_service": "Edit Service",
  "service_name": "Service Name",
  "description": "Description",
  "price": "Price",
  "update_service": "Update Service",
  "add_service": "Add Service",
  "partner_services": "Partner Services",
  "no_services_added_yet": "No services added yet",
  "delete_service": "\"Delete Service\"",
  "are_you_sure_you_want_to_delete_this_service":
      "Are you sure you want to delete this service?",
  "delete": "Delete",
  "failed_to_delete_service": "Failed to delete service",
  "error": "Error",
  "failed_to_update_service": "Failed to update service",
  "current_password": "Current Password",
  "new_password": "New Password",
  "confirm_password": "Confirm Password",
  "update_password": "Update Password",
  "save": "Save",
  "owner_name": "Owner Name",
  "partner_code": "Partner Code",
  "city": "City",
  "district": "District",
  "country": "Country",
  "scan_qr": "Scan QR",
  "align_qr_code_inside_the_frame": "Align QR code inside the frame",
  "enter_code_manually": "Enter Code Manually",
  "please_enter_a_valid_code": "Please enter a valid code",
  "invalid_qr_code": "Invalid QR Code",
  "invalid_coupon": "Invalid coupon",
  "failed_to_load_details": "Failed to load details",
  "validation_failed": "Validation failed",
  "service_confirmation": "Service Confirmation",
  "service_completed": "Service Completed!",
  "order_summary": "Order Summary",
  "paid": "PAID",
  "code_verified": "Code Verified",
  "discount_applied": "Discount Applied",
  "customer_details": "Customer Details",
  "vehicle_info": "Vehicle Info",
  "license_plate": "LICENSE PLATE",
  "confirm_start_wash": "Confirm & Start Wash",
  "payment": "Payment",
  "scan_to_complete_payment": "Scan to complete payment",
  "waiting_for_scan": "Waiting for scan...",
  "total_amount_due": "TOTAL AMOUNT DUE",
  "service_breakdown": "Service Breakdown",
  "done": "Done",
  "invalid_payment_data": "Invalid payment data",
  "failed_to_redeem_coupon": "Failed to redeem coupon",
  "payment_completed": "Payment completed",
  "something_went_wrong": "Something went wrong",
  "select_services": "Select Services",
  "wash_packages": "Wash Packages",
  "no_services_available": "No services available",
  "please_select_a_service_to_continue": "Please select a service to continue",
  "select_service": "Select Service",
  "confirm_order": "Confirm Order",
  "cost_breakdown": "Cost Breakdown",
  "original_price": "Original Price",
  "partner_discount": "Partner Discount",
  "total_to_pay": "Total to Pay",
  "discount_automatically_applied_for_qr_code_customers":
      "Discount automatically applied for QR code customers.",
  "enter_qr_code": "Enter QR Code",
  "submit": "Submit",
  "confirmation": "Confirmation",
  "reload": "Reload",
  "go_settings": "Go to Settings",
  "internet_not_available": "Internet not available",
};
