const Map<String, String> arSA = {
  "english_lables_of_partner_app": "Arabic Lables",
  "choose_your_language": "اختر لغتك",
  "english": "الإنجليزية",
  "arabic": "العربية",
  "continue": "متابعة",
  "partner_login": "تسجيل دخول الشريك",
  "userid": "معرّف المستخدم",
  "enter_your_user_id": "أدخل معرّف المستخدم",
  "password": "كلمة المرور",
  "enter_your_password": "أدخل كلمة المرور",
  "login": "تسجيل الدخول",
  "user_id_is_required": "معرّف المستخدم مطلوب",
  "password_is_required": "كلمة المرور مطلوبة",
  "invalid_credentials": "بيانات الاعتماد غير صالحة",
  "home": "الرئيسية",
  "history": "السجل",
  "profile": "الملف الشخصي",
  "tap_to_scan": "اضغط للمسح",
  "scan_customer_qr_code": "امسح رمز QR الخاص بالعميل",
  "previous_service": "الخدمة السابقة",
  "no_previous_services": "لا توجد خدمات سابقة",
  "customer": "العميل:",
  "vehicle": "المركبة:",
  "admin_payable": "المبلغ المستحق للإدارة:",
  "service_history": "سجل الخدمات",
  "search_service_name_or_customer_name": "ابحث باسم الخدمة أو العميل",
  "recent_activity": "النشاط الأخير",
  "no_history_found": "لم يتم العثور على سجل",
  "total_admin_payable": "إجمالي المستحق للإدارة",
  "jan": "يناير",
  "feb": "فبراير",
  "mar": "مارس",
  "april": "أبريل",
  "may": "مايو",
  "jun": "يونيو",
  "jul": "يوليو",
  "aug": "أغسطس",
  "sep": "سبتمبر",
  "oct": "أكتوبر",
  "nov": "نوفمبر",
  "dec": "ديسمبر",
  "date": "التاريخ",
  "partner": "الشريك",
  "owner": "المالك:",
  "account_settings": "إعدادات الحساب",
  "personal_details": "التفاصيل الشخصية",
  "edit_profile_information": "تعديل معلومات الملف الشخصي",
  "add_services": "إضافة خدمات",
  "add_or_remove_services_offered": "إضافة أو إزالة الخدمات المقدمة",
  "change_password": "تغيير كلمة المرور",
  "update_security_credentials": "تحديث بيانات الأمان",
  "change_language": "تغيير اللغة",
  "log_out": "تسجيل الخروج",
  "sign_out_of_your_account": "تسجيل الخروج من حسابك",
  "are_you_sure_you_want_to_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "cancel": "إلغاء",
  "add_new_service": "إضافة خدمة جديدة",
  "edit_service": "تعديل الخدمة",
  "service_name": "اسم الخدمة",
  "description": "الوصف",
  "price": "السعر",
  "update_service": "تحديث الخدمة",
  "add_service": "إضافة خدمة",
  "partner_services": "خدمات الشريك",
  "no_services_added_yet": "لم تتم إضافة خدمات بعد",
  "delete_service": "حذف الخدمة",
  "are_you_sure_you_want_to_delete_this_service":
      "هل أنت متأكد أنك تريد حذف هذه الخدمة؟",
  "delete": "حذف",
  "failed_to_delete_service": "فشل حذف الخدمة",
  "error": "خطأ",
  "failed_to_update_service": "فشل تحديث الخدمة",
  "current_password": "كلمة المرور الحالية",
  "new_password": "كلمة المرور الجديدة",
  "confirm_password": "تأكيد كلمة المرور",
  "update_password": "تحديث كلمة المرور",
  "save": "حفظ",
  "owner_name": "اسم المالك",
  "partner_code": "رمز الشريك",
  "city": "المدينة",
  "district": "المنطقة",
  "country": "الدولة",
  "scan_qr": "مسح QR",
  "align_qr_code_inside_the_frame": "قم بمحاذاة رمز QR داخل الإطار",
  "enter_code_manually": "إدخال الرمز يدويًا",
  "please_enter_a_valid_code": "يرجى إدخال رمز صالح",
  "invalid_qr_code": "رمز QR غير صالح",
  "invalid_coupon": "قسيمة غير صالحة",
  "failed_to_load_details": "فشل تحميل التفاصيل",
  "validation_failed": "فشل التحقق",
  "service_confirmation": "تأكيد الخدمة",
  "service_completed": "تم إكمال الخدمة!",
  "order_summary": "ملخص الطلب",
  "paid": "مدفوع",
  "code_verified": "تم التحقق من الرمز",
  "discount_applied": "تم تطبيق الخصم",
  "customer_details": "تفاصيل العميل",
  "vehicle_info": "معلومات المركبة",
  "license_plate": "لوحة الترخيص",
  "confirm_start_wash": "تأكيد وبدء الغسيل",
  "payment": "الدفع",
  "scan_to_complete_payment": "امسح لإكمال الدفع",
  "waiting_for_scan": "في انتظار المسح...",
  "total_amount_due": "إجمالي المبلغ المستحق",
  "service_breakdown": "تفصيل الخدمة",
  "done": "تم",
  "invalid_payment_data": "بيانات الدفع غير صالحة",
  "failed_to_redeem_coupon": "فشل استرداد القسيمة",
  "payment_completed": "اكتمل الدفع",
  "something_went_wrong": "حدث خطأ ما",
  "select_services": "اختر الخدمات",
  "wash_packages": "باقات الغسيل",
  "no_services_available": "لا توجد خدمات متاحة",
  "please_select_a_service_to_continue": "يرجى اختيار خدمة للمتابعة",
  "select_service": "اختر الخدمة",
  "confirm_order": "تأكيد الطلب",
  "cost_breakdown": "تفصيل التكلفة",
  "original_price": "السعر الأصلي",
  "partner_discount": "خصم الشريك",
  "total_to_pay": "إجمالي المبلغ للدفع",
  "discount_automatically_applied_for_qr_code_customers":
      "يتم تطبيق الخصم تلقائيًا لعملاء رمز QR.",
  "enter_qr_code": "أدخل رمز QR",
  "submit": "إرسال",
  "confirmation": "تأكيد",
  "reload": "إعادة تحميل",
  "go_settings": "انتقل إلى الإعدادات",
  "internet_not_available": "الإنترنت غير متاح",
};
